name: GrinchSimulator
version: 1.12
api-version: 1.13
main: ro.Fr33styler.GrinchSimulator.Main
author: Fr33styler
softdepend: [Multiverse-Core, MultiWorld]
commands:
  grinch:
    description: This is the main plugin command.
    aliases: [gs]